# Parent image is the Amplicon-Architect-Environment
FROM genepattern/amplicon-architect-environment:v2.8

# COPY the wrapper script over
COPY run_aa.py /opt/genepatt
COPY download_ref.sh /opt/genepatt
COPY run_aa_v2.sh /opt/genepatt
