# Parent image is the Amplicon-Architect-Environment
FROM genepattern/amplicon-architect-environment:v2

# COPY the wrapper script over
COPY run_paa.sh /opt/genepatt
COPY run_aa_v2.sh /opt/genepatt


# COPY TEST FILES (Testing Only)
# COPY testfiles/* /opt/genepatt/testdata
